datasets : "analysis/configs/nestedness_simulations/datasets.tsv"
fasta_ref: "analysis/input_data/pfalciparum/ref_genome/Pfalciparum.genome.fasta"

k : 10

num_simu_paths : 5
simu_read_params: {err_scaling: [0, -20], fcov: [40]}
read_len : 75
