genes: "analysis/input_data/gene_lists/gene_list_1.txt"
flank_size: 5000

pf_release_3:
  fasta: "analysis/input_data/ref_genomes/P_falciparum_2015_08/Pfalciparum.genome.fasta.gz"
  fai: "analysis/input_data/ref_genomes/P_falciparum_2015_08/Pfalciparum.genome.fasta.gz.fai"
  gff: "analysis/input_data/ref_genomes/P_falciparum_2015_08/Pfalciparum.gff3"
  cortex_vcf_prefix: "tmp_work"
  cortex_vcf_list: "tmp_work/vcf_list.txt"

make_prg:
  max_nest: [1, 5]
  min_match: 7


