sample_tsv: "analysis/input_data/pfalciparum/pf3k/pf3k_release_5.tsv"
ilmn_reads_dir: "analysis/input_data/pfalciparum/pf3k/fastqs" # Must be named this way, is referred to in analysis/workflows/common_utils.py

prg: "analysis/outputs/make_prgs/pf_4surfants/prg_mn5_mml7" # Implies make_prgs workflow has been run on the pf_4surfants gene list
gene_list_name: "pf_4surfants"
prg_ref: "analysis/input_data/pfalciparum/ref_genome/Pfalciparum.genome.fasta"
genes_bed: "analysis/input_data/msps_dimorphism/analysed_regions.bed"
