prg_name: "pf_4surfants"
genes: "analysis/input_data/make_prgs/gene_lists/pf_4surfants.txt"
flank_size: 5000

genome_fasta: "analysis/input_data/pfalciparum/ref_genome/Pfalciparum.genome.fasta"
genome_fai: "analysis/input_data/pfalciparum/ref_genome/Pfalciparum.genome.fasta.fai"

initial_bed: "analysis/input_data/make_prgs/beds/pf_4surfants.bed" # made from script analysis/input_data/make_prgs/beds/scripts/make_initial_beds.sh

vcf_list: "analysis/input_data/pfalciparum/pf3k/vcf_list.txt"
vcf_prefix: "analysis/input_data/pfalciparum/pf3k/vcfs"


make_prg:
  max_nest: [1, 5]
  min_match: 7


