prg_name: "pf_DBLMSPs"
genes: "analysis/input_data/make_prgs/gene_lists/pf_DBLMSPs.txt"
flank_size: 5000

genome_fasta: "analysis/input_data/pfalciparum/ref_genome/Pfalciparum.genome.fasta"
genome_fai: "analysis/input_data/pfalciparum/ref_genome/Pfalciparum.genome.fasta"

initial_bed: "analysis/input_data/make_prgs/beds/tb_bigdel.bed" # made from script analysis/input_data/scripts/make_prgs/bigdel_vcfs_to_bed.sh

  vcf_list: "analysis/input/pfalciparum/pf3k/vcf_list.txt"
  #vcf_prefix: "/nfs/research1/zi/mirror/oxford/cycloid/data3/projects/pf3k/discovery_gt/release3_for_first_paper" # noah
  vcf_prefix: "/nfs/leia/research/iqbal/mirror2/oxford/cycloid/data3/pf3k/discovery_gt/release3_for_first_paper/release3_for_first_paper" # yoda


make_prg:
  max_nest: [1, 5]
  min_match: 7


