starting_prg: "analysis/outputs/make_prgs/pf_4surfants/prg_mn5_mml7"

kmer_size: 10

sample_tsv: "analysis/input_data/pfalciparum/pacb_ilmn/data_accessions.tsv"
assemblies_dir: "analysis/input_data/pfalciparum/pacb_ilmn/pacb_assemblies"
ilmn_reads_dir: "analysis/input_data/pfalciparum/pacb_ilmn/ilmn_reads"
